steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'gcr.io/${PROJECT_ID}/helloworld-image:${_SHORT_SHA}', '.' ]
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'push', 'gcr.io/${PROJECT_ID}/helloworld-image:${_SHORT_SHA}']
# - name: "gcr.io/cloud-builders/gke-deploy"
#   args:
#   - run
#   - --filename=yaml/release
#   - --image=gcr.io/${PROJECT_ID}/helloworld-image:${_SHORT_SHA}
#   - --location=asia-east1
#   - --cluster=autopilot-cluster-1
- name: gcr.io/cloud-builders/gcloud
  entrypoint: bash
  args:
    - -c
    - |
      gcloud container clusters get-credentials autopilot-cluster-1  \
       --zone asia-east1 \
       --project natural-night-463201-t0

      kubectl set image -f yaml/release/server-deployment.yaml helloworld1=gcr.io/${PROJECT_ID}/helloworld-image:${_SHORT_SHA} \
          --local --dry-run=client -o yaml > ci-tmp.yaml && mv ci-tmp.yaml yaml/release/server-deployment.yaml

      kubectl apply --filename=yaml/release

tags: ['gcp-cloud-build-sample-build']

options:
  logging: CLOUD_LOGGING_ONLY