steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'asia-east1-docker.pkg.dev/natural-night-463201-t0/test/helloworld-image:${_SHORT_SHA}', '.' ]
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'push', 'asia-east1-docker.pkg.dev/natural-night-463201-t0/test/helloworld-image:${_SHORT_SHA}']

tags: ['gcp-cloud-build-sample-build']

serviceAccount: test-build@natural-night-463201-t0.iam.gserviceaccount.com
options:
  logging: CLOUD_LOGGING_ONLY
  pubsubTopic: projects/phonic-chariot-464007-n8/topics/cloud-builds-nt
  substitutionOption: 'ALLOW_LOOSE'
