steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'gcr.io/${PROJECT_ID}/helloworld-image:${_SHORT_SHA}', '.' ]
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'push', 'gcr.io/${PROJECT_ID}/helloworld-image:${_SHORT_SHA}']

tags: ['gcp-cloud-build-sample-build']

options:
  logging: CLOUD_LOGGING_ONLY

