steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/helloworld-image:2.0', '.' ]
- name: "gcr.io/cloud-builders/gke-deploy"
  args:
  - run
  - --filename=yaml
  - --image=gcr.io/$PROJECT_ID/helloworld-image:2.0
  - --location=asia-east1
  - --cluster=autopilot-cluster-1

images:
- 'gcr.io/$PROJECT_ID/helloworld-image:2.0'

tags: ['gcp-cloud-build-sample-build']

options:
  logging: CLOUD_LOGGING_ONLY