steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'gcr.io/${PROJECT_ID}/helloworld-image:${_SHORT_SHA}', '.' ]
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'push', 'gcr.io/${PROJECT_ID}/helloworld-image:${_SHORT_SHA}']
# - name: "gcr.io/cloud-builders/gke-deploy"
#   args:
#   - run
#   - --filename=yaml/release
#   - --image=gcr.io/${PROJECT_ID}/helloworld-image:${_SHORT_SHA}
#   - --location=asia-east1
#   - --cluster=autopilot-cluster-1
- name: gcr.io/cloud-builders/gcloud
  entrypoint: bash
  args:
    - -c
    - |
      cluster=autopilot-cluster-1
      local=asia-east1
      project_id=natural-night-463201-t0
      yaml_dir=yaml/release
      yaml_file=yaml/release/server-deployment.yaml
      image_name=helloworld1
      image=gcr.io/${PROJECT_ID}/helloworld-image:${_SHORT_SHA}

      gcloud container clusters get-credentials $$cluster  \
       --zone $$local \
       --project $$project_id
      kubectl set image -f $$yaml_file $$image_name=$$image \
          --local --dry-run=client -o yaml > ci-tmp.yaml 
      mv ci-tmp.yaml $$yaml_file
      kubectl apply --filename=$$yaml_dir

tags: ['gcp-cloud-build-sample-build']

options:
  logging: CLOUD_LOGGING_ONLY