steps:
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args: 
  - '-c'
  - |
    COMMIT_MSG=$(git log -1 --pretty=%B)
    echo "Commit message: $$COMMIT_MSG"
    MANUALLY_CALL=$(echo "$_MANUALLY_CALL" | cut -d',' -f1)
    echo "manually call: $$MANUALLY_CALL"
    TIMESTAMP=$(date +"%Y%m%d%H%M%S")
    if [[ "$$MANUALLY_CALL" == *"build"* ]]; then
      echo "Triggering build..."
      gcloud builds submit --config=cloudbuild-build.yaml --region=us-central1 --substitutions=_SHORT_SHA="auto_$SHORT_SHA.$$TIMESTAMP"
    elif [[ "$$MANUALLY_CALL" == *"deploy"* ]]; then
      echo "Triggering deploy..."
      gcloud builds submit --config=cloudbuild-deploy.yaml --region=us-central1 --substitutions=_SHORT_SHA="auto_$SHORT_SHA.$$TIMESTAMP"
    elif [[ "$$COMMIT_MSG" == *"[build]"* ]]; then
      echo "Triggering build..."
      gcloud builds submit --config=cloudbuild-build.yaml --region=us-central1 --substitutions=_SHORT_SHA="auto_$SHORT_SHA.$$TIMESTAMP"
    elif [[ "$$COMMIT_MSG" == *"[deploy]"* ]]; then
      echo "Triggering deploy..."
      gcloud builds submit --config=cloudbuild-deploy.yaml --region=us-central1 --substitutions=_SHORT_SHA="auto_$SHORT_SHA.$$TIMESTAMP"
    else 
        echo "No [build] or [deploy] detected in git message, skip build."
    fi
options:
  logging: CLOUD_LOGGING_ONLY
substitutions:
  _MANUALLY_CALL: "none,build,deploy"