steps:
- name: 'bash'
  script: |
    #!/usr/bin/env bash
    COMMIT_MSG=$(git log -1 --pretty=%B)
    echo "Commit message: $COMMIT_MSG"
    if [[ "$COMMIT_MSG" != *"[build]"* ]]; then
      echo "No [build] tag in commit message. Skipping build."
      exit 0
    fi
- name: 'docker'
  args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/helloworld-image', '.' ]

images:
- 'gcr.io/$PROJECT_ID/helloworld-image'

tags: ['gcp-cloud-build-sample-build']
