steps:
- name: 'docker'
  args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/helloworld-image', '.' ]

images:
- 'gcr.io/$PROJECT_ID/helloworld-image'

tags: ['gcp-cloud-build-sample-build']
options:
  logging: CLOUD_LOGGING_ONLY