apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "helloworld1"
  namespace: "default"
  labels:
    app: "helloworld1"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "helloworld1"
  template:
    metadata:
      labels:
        app: "helloworld1"
    spec:
      containers:
      - name: "helloworld1"
        image: "gcr.io/natural-night-463201-t0/helloworld-image:2.0"